// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/plugin/plugin.proto

#include "proto/plugin/plugin.pb.h"
#include "proto/plugin/plugin.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace plugin {

static const char* PluginService_method_names[] = {
  "/plugin.PluginService/Init",
  "/plugin.PluginService/HandleRequest",
  "/plugin.PluginService/HealthCheck",
  "/plugin.PluginService/Shutdown",
};

std::unique_ptr< PluginService::Stub> PluginService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PluginService::Stub> stub(new PluginService::Stub(channel, options));
  return stub;
}

PluginService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Init_(PluginService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HandleRequest_(PluginService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HealthCheck_(PluginService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Shutdown_(PluginService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PluginService::Stub::Init(::grpc::ClientContext* context, const ::plugin::InitRequest& request, ::plugin::InitResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::plugin::InitRequest, ::plugin::InitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Init_, context, request, response);
}

void PluginService::Stub::async::Init(::grpc::ClientContext* context, const ::plugin::InitRequest* request, ::plugin::InitResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::plugin::InitRequest, ::plugin::InitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Init_, context, request, response, std::move(f));
}

void PluginService::Stub::async::Init(::grpc::ClientContext* context, const ::plugin::InitRequest* request, ::plugin::InitResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Init_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::plugin::InitResponse>* PluginService::Stub::PrepareAsyncInitRaw(::grpc::ClientContext* context, const ::plugin::InitRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::plugin::InitResponse, ::plugin::InitRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Init_, context, request);
}

::grpc::ClientAsyncResponseReader< ::plugin::InitResponse>* PluginService::Stub::AsyncInitRaw(::grpc::ClientContext* context, const ::plugin::InitRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginService::Stub::HandleRequest(::grpc::ClientContext* context, const ::plugin::RequestContext& request, ::plugin::ResponseContext* response) {
  return ::grpc::internal::BlockingUnaryCall< ::plugin::RequestContext, ::plugin::ResponseContext, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HandleRequest_, context, request, response);
}

void PluginService::Stub::async::HandleRequest(::grpc::ClientContext* context, const ::plugin::RequestContext* request, ::plugin::ResponseContext* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::plugin::RequestContext, ::plugin::ResponseContext, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleRequest_, context, request, response, std::move(f));
}

void PluginService::Stub::async::HandleRequest(::grpc::ClientContext* context, const ::plugin::RequestContext* request, ::plugin::ResponseContext* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::plugin::ResponseContext>* PluginService::Stub::PrepareAsyncHandleRequestRaw(::grpc::ClientContext* context, const ::plugin::RequestContext& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::plugin::ResponseContext, ::plugin::RequestContext, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HandleRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::plugin::ResponseContext>* PluginService::Stub::AsyncHandleRequestRaw(::grpc::ClientContext* context, const ::plugin::RequestContext& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandleRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginService::Stub::HealthCheck(::grpc::ClientContext* context, const ::plugin::Empty& request, ::plugin::HealthStatus* response) {
  return ::grpc::internal::BlockingUnaryCall< ::plugin::Empty, ::plugin::HealthStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HealthCheck_, context, request, response);
}

void PluginService::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::plugin::Empty* request, ::plugin::HealthStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::plugin::Empty, ::plugin::HealthStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, std::move(f));
}

void PluginService::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::plugin::Empty* request, ::plugin::HealthStatus* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::plugin::HealthStatus>* PluginService::Stub::PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::plugin::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::plugin::HealthStatus, ::plugin::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HealthCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::plugin::HealthStatus>* PluginService::Stub::AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::plugin::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHealthCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PluginService::Stub::Shutdown(::grpc::ClientContext* context, const ::plugin::Empty& request, ::plugin::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::plugin::Empty, ::plugin::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Shutdown_, context, request, response);
}

void PluginService::Stub::async::Shutdown(::grpc::ClientContext* context, const ::plugin::Empty* request, ::plugin::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::plugin::Empty, ::plugin::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Shutdown_, context, request, response, std::move(f));
}

void PluginService::Stub::async::Shutdown(::grpc::ClientContext* context, const ::plugin::Empty* request, ::plugin::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Shutdown_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::plugin::Empty>* PluginService::Stub::PrepareAsyncShutdownRaw(::grpc::ClientContext* context, const ::plugin::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::plugin::Empty, ::plugin::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Shutdown_, context, request);
}

::grpc::ClientAsyncResponseReader< ::plugin::Empty>* PluginService::Stub::AsyncShutdownRaw(::grpc::ClientContext* context, const ::plugin::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncShutdownRaw(context, request, cq);
  result->StartCall();
  return result;
}

PluginService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginService::Service, ::plugin::InitRequest, ::plugin::InitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::plugin::InitRequest* req,
             ::plugin::InitResponse* resp) {
               return service->Init(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginService::Service, ::plugin::RequestContext, ::plugin::ResponseContext, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::plugin::RequestContext* req,
             ::plugin::ResponseContext* resp) {
               return service->HandleRequest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginService::Service, ::plugin::Empty, ::plugin::HealthStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::plugin::Empty* req,
             ::plugin::HealthStatus* resp) {
               return service->HealthCheck(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PluginService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PluginService::Service, ::plugin::Empty, ::plugin::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PluginService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::plugin::Empty* req,
             ::plugin::Empty* resp) {
               return service->Shutdown(ctx, req, resp);
             }, this)));
}

PluginService::Service::~Service() {
}

::grpc::Status PluginService::Service::Init(::grpc::ServerContext* context, const ::plugin::InitRequest* request, ::plugin::InitResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginService::Service::HandleRequest(::grpc::ServerContext* context, const ::plugin::RequestContext* request, ::plugin::ResponseContext* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginService::Service::HealthCheck(::grpc::ServerContext* context, const ::plugin::Empty* request, ::plugin::HealthStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PluginService::Service::Shutdown(::grpc::ServerContext* context, const ::plugin::Empty* request, ::plugin::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace plugin
#include <grpcpp/ports_undef.inc>

