// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/plugin/plugin.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus_Status int32

const (
	HealthStatus_UNKNOWN     HealthStatus_Status = 0
	HealthStatus_SERVING     HealthStatus_Status = 1
	HealthStatus_NOT_SERVING HealthStatus_Status = 2
)

// Enum value maps for HealthStatus_Status.
var (
	HealthStatus_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthStatus_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthStatus_Status) Enum() *HealthStatus_Status {
	p := new(HealthStatus_Status)
	*p = x
	return p
}

func (x HealthStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plugin_plugin_proto_enumTypes[0].Descriptor()
}

func (HealthStatus_Status) Type() protoreflect.EnumType {
	return &file_proto_plugin_plugin_proto_enumTypes[0]
}

func (x HealthStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus_Status.Descriptor instead.
func (HealthStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_plugin_plugin_proto_rawDescGZIP(), []int{5, 0}
}

type RequestContext struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method    string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path      string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Headers   map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body      []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Params    map[string]string      `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Path parameters
	Query     map[string]string      `protobuf:"bytes,7,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`   // Query parameters
	// User info
	UserId        string `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string `protobuf:"bytes,9,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_proto_plugin_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_proto_plugin_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *RequestContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestContext) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestContext) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestContext) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestContext) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RequestContext) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *RequestContext) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *RequestContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ResponseContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseContext) Reset() {
	*x = ResponseContext{}
	mi := &file_proto_plugin_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseContext) ProtoMessage() {}

func (x *ResponseContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseContext.ProtoReflect.Descriptor instead.
func (*ResponseContext) Descriptor() ([]byte, []int) {
	return file_proto_plugin_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseContext) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ResponseContext) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ResponseContext) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ResponseContext) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_proto_plugin_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_proto_plugin_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *InitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_plugin_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_plugin_plugin_proto_rawDescGZIP(), []int{4}
}

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus_Status    `protobuf:"varint,1,opt,name=status,proto3,enum=plugin.HealthStatus_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_proto_plugin_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_proto_plugin_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HealthStatus) GetStatus() HealthStatus_Status {
	if x != nil {
		return x.Status
	}
	return HealthStatus_UNKNOWN
}

func (x *HealthStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_plugin_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_plugin_proto_rawDesc = "" +
	"\n" +
	"\x19proto/plugin/plugin.proto\x12\x06plugin\"\x8a\x04\n" +
	"\x0eRequestContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12=\n" +
	"\aheaders\x18\x04 \x03(\v2#.plugin.RequestContext.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12:\n" +
	"\x06params\x18\x06 \x03(\v2\".plugin.RequestContext.ParamsEntryR\x06params\x127\n" +
	"\x05query\x18\a \x03(\v2!.plugin.RequestContext.QueryEntryR\x05query\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\t \x01(\tR\btenantId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x01\n" +
	"\x0fResponseContext\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12>\n" +
	"\aheaders\x18\x02 \x03(\v2$.plugin.ResponseContext.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x01\n" +
	"\vInitRequest\x127\n" +
	"\x06config\x18\x01 \x03(\v2\x1f.plugin.InitRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\fInitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\a\n" +
	"\x05Empty\"\x92\x01\n" +
	"\fHealthStatus\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.plugin.HealthStatus.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xe2\x01\n" +
	"\rPluginService\x121\n" +
	"\x04Init\x12\x13.plugin.InitRequest\x1a\x14.plugin.InitResponse\x12@\n" +
	"\rHandleRequest\x12\x16.plugin.RequestContext\x1a\x17.plugin.ResponseContext\x122\n" +
	"\vHealthCheck\x12\r.plugin.Empty\x1a\x14.plugin.HealthStatus\x12(\n" +
	"\bShutdown\x12\r.plugin.Empty\x1a\r.plugin.EmptyB/Z-github.com/polyshift/microkernel/proto/pluginb\x06proto3"

var (
	file_proto_plugin_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_plugin_proto_rawDescData []byte
)

func file_proto_plugin_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_plugin_proto_rawDesc), len(file_proto_plugin_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_plugin_proto_rawDescData
}

var file_proto_plugin_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_plugin_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_plugin_plugin_proto_goTypes = []any{
	(HealthStatus_Status)(0), // 0: plugin.HealthStatus.Status
	(*RequestContext)(nil),   // 1: plugin.RequestContext
	(*ResponseContext)(nil),  // 2: plugin.ResponseContext
	(*InitRequest)(nil),      // 3: plugin.InitRequest
	(*InitResponse)(nil),     // 4: plugin.InitResponse
	(*Empty)(nil),            // 5: plugin.Empty
	(*HealthStatus)(nil),     // 6: plugin.HealthStatus
	nil,                      // 7: plugin.RequestContext.HeadersEntry
	nil,                      // 8: plugin.RequestContext.ParamsEntry
	nil,                      // 9: plugin.RequestContext.QueryEntry
	nil,                      // 10: plugin.ResponseContext.HeadersEntry
	nil,                      // 11: plugin.InitRequest.ConfigEntry
}
var file_proto_plugin_plugin_proto_depIdxs = []int32{
	7,  // 0: plugin.RequestContext.headers:type_name -> plugin.RequestContext.HeadersEntry
	8,  // 1: plugin.RequestContext.params:type_name -> plugin.RequestContext.ParamsEntry
	9,  // 2: plugin.RequestContext.query:type_name -> plugin.RequestContext.QueryEntry
	10, // 3: plugin.ResponseContext.headers:type_name -> plugin.ResponseContext.HeadersEntry
	11, // 4: plugin.InitRequest.config:type_name -> plugin.InitRequest.ConfigEntry
	0,  // 5: plugin.HealthStatus.status:type_name -> plugin.HealthStatus.Status
	3,  // 6: plugin.PluginService.Init:input_type -> plugin.InitRequest
	1,  // 7: plugin.PluginService.HandleRequest:input_type -> plugin.RequestContext
	5,  // 8: plugin.PluginService.HealthCheck:input_type -> plugin.Empty
	5,  // 9: plugin.PluginService.Shutdown:input_type -> plugin.Empty
	4,  // 10: plugin.PluginService.Init:output_type -> plugin.InitResponse
	2,  // 11: plugin.PluginService.HandleRequest:output_type -> plugin.ResponseContext
	6,  // 12: plugin.PluginService.HealthCheck:output_type -> plugin.HealthStatus
	5,  // 13: plugin.PluginService.Shutdown:output_type -> plugin.Empty
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_plugin_plugin_proto_init() }
func file_proto_plugin_plugin_proto_init() {
	if File_proto_plugin_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_plugin_proto_rawDesc), len(file_proto_plugin_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_plugin_proto_depIdxs,
		EnumInfos:         file_proto_plugin_plugin_proto_enumTypes,
		MessageInfos:      file_proto_plugin_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_plugin_proto = out.File
	file_proto_plugin_plugin_proto_goTypes = nil
	file_proto_plugin_plugin_proto_depIdxs = nil
}
